@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# Create account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "admin@root.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "admin@root.com",
    "password": "123456"
}

###

# @name create-movie
POST {{baseUrl}}/create-movie
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Interstellar",
    "year": 2014,
    "director": "Christopher Nolan",
    "genre": "Sci-Fi",
    "synopsis": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "actors": [
        "Matthew McConaughey",
        "Anne Hathaway",
        "Jessica Chastain",
        "Michael Caine"
    ],
    "image": "https://example.com/movie_2.jpg"
}

###

# @name get-movie
GET {{baseUrl}}/movies?page=2
Content-Type: application/json

###

# @name get-movie-aggregate-directors
GET {{baseUrl}}/movie-aggregates/directors
Content-Type: application/json
###

# @name get-movie-aggregate-genres
GET {{baseUrl}}/movie-aggregates/genres
Content-Type: application/json

###

# @name post-rating
POST {{baseUrl}}/vote
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "movieId": "9f8469ec-3dc4-4b06-a612-9d29590cca3e",
    "value": 4
}