version: '3.8'

services:
  postgres:
    container_name: globo-postgres
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: psglobo
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres